spring:
  datasource:
    url: jdbc:h2:file:./h2-db/skiply-student-db;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: ${DB_USER:sa}
    password: ${DB_PWD:password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # Refer: https://www.baeldung.com/spring-open-session-in-view#2-pattern-or-anti-pattern
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

