DROP SCHEMA IF EXISTS "student" CASCADE;

CREATE SCHEMA "student";

DROP TABLE IF EXISTS "student"."students" CASCADE;

CREATE TABLE "student"."students" (
  "student_id" CHARACTER VARYING PRIMARY KEY NOT NULL,
  "student_name" CHARACTER VARYING NOT NULL,
  "grade" CHARACTER VARYING NOT NULL,
  "mobile_number" CHARACTER VARYING,
  "school_name" CHARACTER VARYING NOT NULL
);